name: CI

on:
  push:
  pull_request:

jobs:
  lint-validate-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      
      - name: Terraform Init
        run: |
          cd terraform/envs/prod
          terraform init -backend=false

      - name: Terraform Format Check
        run: |
          cd terraform/envs/prod
          terraform fmt -check -recursive

      - name: Terraform Validate
        run: |
          cd terraform/envs/prod
          terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3

      - name: Init TFLint
        run: |
          cd terraform/envs/prod
          tflint --init

      - name: Run TFLint
        run: |
          cd terraform/envs/prod
          tflint -f compact

      # python 
      - name: Install Python Lint Tools
        run: |
          pip install flake8 black

      - name: Run Flake8 (Lint Check)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Check Formatting with Black
        run: |
          black --check .